openapi: 3.0.3

info:
  title: Kiskotaan OpenAPI, players service
  version: 0.1.0
  description: API definition for Kiskotaan backend's players service.

tags:
  - name: Players
    description: CRUD operations for handling players.

servers:
  - url: http://localhost:8081/api/

paths:
  /players:
    $ref: "./players/paths.yaml#/Players"
  /players/{id}:
    $ref: "./players/paths.yaml#/Player"

components:
  schemas:
    NewPlayer:
      $ref: "./players/schemas.yaml#/NewPlayer"
    Player:
      $ref: "./players/schemas.yaml#/Player"
    ErrorBody:
      $ref: "./errors/schemas.yaml#/ErrorBody"
