version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: maven
    directory: courses-service
    schedule:
      interval: weekly

  - package-ecosystem: maven
    directory: players-service
    schedule:
      interval: weekly
