version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: maven
    directories:
      - courses-service
      - players-service
      - queries-service
      - queries-service-streams
      - scorecards-service
    groups:
      quarkus:
        patterns:
          - "quarkus*"
        update-types:
          - "patch"
          - "minor"
    schedule:
      interval: weekly
