version: '3.8'

services:
  # Kafka message broker using KRaft instead of ZooKeeper for simpler development experience.
  kafka:
    container_name: kafka
    environment:
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_BROKER_ID: 1
      KAFKA_ENABLE_KRAFT: yes
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@127.0.0.1:9093
    image: bitnami/kafka
    networks:
      - kafka
    ports:
      - 9092:9092

  # Courses service
  postgres:
    container_name: postgres
    environment:
      POSTGRES_DATABASE: testdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    image: postgres
    networks:
      - db
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgres
      - ./db:/docker-entrypoint-initdb.d

  courses_service:
    container_name: courses_service
    depends_on:
      - kafka
      - postgres
    environment:
      db_url: jdbc:postgresql://postgres:5432/testdb
      db_username: admin
      db_password: admin
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    expose:
      - 8082
    image: mikaalaoutinen/courses-service
    networks:
      - db
      - kafka
    ports:
      - 8082:8082

networks:
  db:
    driver: bridge
  kafka:
    driver: bridge

volumes:
  pg_data:
