version: '3.8'

services:
  postgres:
    container_name: player_db
    environment:
      POSTGRES_DATABASE: player_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    image: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgres
      - ./scripts/data.csv:/data/data.csv
      - ./scripts:/docker-entrypoint-initdb.d

volumes:
  pg_data:
