server:
  port: 8081

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${db_url:jdbc:postgresql://localhost:5432/player_db}
    username: ${db_username:admin}
    password: ${db_password:admin}

  jpa:
    hibernate:
      ddl-auto: none

  kafka:
    bootstrap-servers: ${kafka_url:localhost:9092}
    producer:
      client-id: players-producer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  liquibase:
    change-log: db/changelog.yaml
    contexts: all
