apicurio-url: ${apicurio_url:http://localhost:8000}

server:
  port: 8081

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${db_url:jdbc:postgresql://localhost:5432/players_db}
    username: ${db_username:admin}
    password: ${db_password:admin}

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

  kafka:
    bootstrap-servers: ${kafka_url:localhost:9092}
    producer:
      client-id: players-producer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.apicurio.registry.serde.avro.AvroKafkaSerializer
      properties:
        apicurio:
          registry:
            auto-register: true
            url: ${apicurio-url}

  liquibase:
    change-log: db/changelog.yaml
    contexts: all,dev # dev context inserts test data into db
