developerName: Mika Alaoutinen

# Package settings
apiPackage: mikaa.api
modelPackage: mikaa.model
sourcePackage: src

# code generation settings
documentationProvider: none
implicitHeaders: true
interfaceOnly: true
modelNameSuffix: DTO
openApiNullable: false
performBeanValidation: true
skipDefaultInterface: true
useTags: true
