server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/players_db
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
