server:
  error:
    include-stacktrace: on_param
  port: 8081
  servlet:
    context-path: /api

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/player_db
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
