server:
  port: 8081
  servlet:
    context-path: /api

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/player_db
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: none

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      client-id: players-consumer
      group-id: players-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
    producer:
      client-id: players-producer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
