greeting:
  message: "hello"

log:
  enabled: true
  level: info

mp:
  messaging:
    outgoing:
      words-out:
        topic: "words"
    incoming:
      words-in:
        auto:
          offset:
            reset: "earliest"
        topic: "words"
