quarkus:
  http:
    port: 8085
    root-path: /api

log:
  enabled: true
  level: info

mp:
  messaging:
    incoming:
      courses-in:
        auto:
          offset:
            reset: "earliest"
        topic: "courses"
      players-in:
        auto:
          offset:
            reset: "earliest"
        topic: "players"
