logging-settings:
  enabled: true
  level: info

quarkus:
  http:
    port: 8085

mp:
  messaging:
    incoming:
      courses-in:
        auto:
          offset:
            reset: "earliest"
        topic: "courses"
      holes-in:
        auto:
          offset:
            reset: "earliest"
        topic: "holes"
      players-in:
        auto:
          offset:
            reset: "earliest"
        topic: "players"
