@url = http://localhost:8083/scorecards

### Add score for Laajis
POST {{url}}/1/scores HTTP/1.1
Content-Type: application/json

{
  "playerId": 101,
  "hole": 5,
  "score": 5
}

### Try to add score for score card that doesn't exist
POST {{url}}/404/scores HTTP/1.1
Content-Type: application/json

{
  "playerId": 101,
  "hole": 1,
  "score": 2
}

### Try to add score for player that doesn't exist
POST {{url}}/1/scores HTTP/1.1
Content-Type: application/json

{
  "playerId": 404,
  "hole": 1,
  "score": 2
}
