@url = http://localhost:8082/courses

### Update hole 1 for Laajavuori
PUT {{url}}/1/holes/1 HTTP/1.1
Content-Type: application/json

{
  "par": 4,
  "distance": 123
}

### Try to update hole that doesn't exist
PUT {{url}}/1/holes/28 HTTP/1.1
Content-Type: application/json

{
  "par": 4,
  "distance": 123
}
