@url = http://localhost:8083/scorecards

### Add new score card
POST {{url}} HTTP/1.1
Content-Type: application/json

{
  "courseId": 7,
  "playerIds": [ 3, 4 ]
}

### Try to add new score card for course that doesn't exist
POST {{url}} HTTP/1.1
Content-Type: application/json

{
  "courseId": 99,
  "playerIds": [ 111 ]
}
