@url = http://localhost:8082/courses

### get all courses
GET {{url}} HTTP/1.1

### get courses filtered by min and max holes
GET {{url}}?holesMin=9&holesMax=18 HTTP/1.1

### get courses filtered by max holes
GET {{url}}?&holesMax=18 HTTP/1.1

### get one course
GET {{url}}/1 HTTP/1.1

### get course that doesn't exist
GET {{url}}/99 HTTP/1.1
