@url = http://localhost:8082/courses

### Add new course with one hole
POST {{url}} HTTP/1.1
Content-Type: application/json

{
  "name": "New course",
  "holes": [
    {
      "number": 1,
      "par": 3,
      "distance": 95
    }
  ]
}

### Add invalid course with no holes
POST {{url}} HTTP/1.1
Content-Type: application/json

{
  "name": "Invalid course"
}
