mp:
  messaging:
    incoming:
      courses-in:
        auto:
          offset:
            reset: "earliest"
        topic: "Courses.course"
      holes-in:
        auto:
          offset:
            reset: "earliest"
        topic: "Courses.hole"
      players-in:
        auto:
          offset:
            reset: "earliest"
        topic: "Players.player"
      scorecards-in:
        auto:
          offset:
            reset: "earliest"
        topic: "Scorecards.scorecard"
      scores-in:
        auto:
          offset:
            reset: "earliest"
        topic: "Scorecards.score"
