mp:
  messaging:
    incoming:
      course-added:
        auto:
          offset:
            reset: "earliest"
        topic: "Courses.course_added"
      course-deleted:
        auto:
          offset:
            reset: "earliest"
        topic: "Courses.course_deleted"
      course-updated:
        auto:
          offset:
            reset: "earliest"
        topic: "Courses.course_updated"
      hole-added:
        auto:
          offset:
            reset: "earliest"
        topic: "Courses.hole_added"
      hole-deleted:
        auto:
          offset:
            reset: "earliest"
        topic: "Courses.hole_deleted"
      hole-updated:
        auto:
          offset:
            reset: "earliest"
        topic: "Courses.hole_updated"

      player-added:
        auto:
          offset:
            reset: "earliest"
        topic: "Players.player_added"
      player-deleted:
        auto:
          offset:
            reset: "earliest"
        topic: "Players.player_deleted"
      player-updated:
        auto:
          offset:
            reset: "earliest"
        topic: "Players.player_updated"

      scorecard-added:
        auto:
          offset:
            reset: "earliest"
        topic: "Scorecards.scorecard_added"
      scorecard-deleted:
        auto:
          offset:
            reset: "earliest"
        topic: "Scorecards.scorecard_deleted"
      score-added:
        auto:
          offset:
            reset: "earliest"
        topic: "Scorecards.score_added"
      score-deleted:
        auto:
          offset:
            reset: "earliest"
        topic: "Scorecards.score_deleted"
