-- changeset mikaa:create_table_player
CREATE TABLE player (
  id            bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  external_id   bigint        UNIQUE NOT NULL,
  first_name    varchar(50)   NOT NULL,
  last_name     varchar(50)   NOT NULL
);
