-- changeset mikaa:create_table_scorecard
CREATE TABLE scorecard (
  id            bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id     bigint        NOT NULL
  
  CONSTRAINT fk_course FOREIGN KEY(course_id) REFERENCES course(id)
);
