-- changeset mikaa:create_table_score
CREATE TABLE score (
  id            bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hole          integer       NOT NULL,
  score         integer       NOT NULL,
  player_id     bigint        NOT NULL,
  scorecard_id  bigint        NOT NULL

  CONSTRAINT fk_player FOREIGN KEY(player_id) REFERENCES player(id)
  CONSTRAINT fk_scorecard FOREIGN KEY(scorecard_id) REFERENCES scorecard(id)
);
