quarkus:
  hibernate-orm:
    validate-in-dev-mode: true
  http:
    port: 8083
  liquibase:
    change-log: db/changelog.yaml
    contexts: all,dev # dev context inserts test data into db
    migrate-at-start: true

mp:
  messaging:
    connector:
      smallrye-kafka:
        apicurio:
          registry:
            auto-register: true

    incoming:
      course-added:
        auto:
          offset:
            reset: "earliest"
        connector: smallrye-kafka
        topic: "Courses.course_added"
      course-deleted:
        auto:
          offset:
            reset: "earliest"
        connector: smallrye-kafka
        topic: "Courses.course_deleted"
      course-updated:
        auto:
          offset:
            reset: "earliest"
        connector: smallrye-kafka
        topic: "Courses.course_updated"
      hole-added:
        auto:
          offset:
            reset: "earliest"
        connector: smallrye-kafka
        topic: "Courses.hole_added"
      hole-deleted:
        auto:
          offset:
            reset: "earliest"
        connector: smallrye-kafka
        topic: "Courses.hole_deleted"
      hole-updated:
        auto:
          offset:
            reset: "earliest"
        connector: smallrye-kafka
        topic: "Courses.hole_updated"
      player-added:
        auto:
          offset:
            reset: "earliest"
        connector: smallrye-kafka
        topic: "Players.player_added"
      player-deleted:
        auto:
          offset:
            reset: "earliest"
        connector: smallrye-kafka
        topic: "Players.player_deleted"
      player-updated:
        auto:
          offset:
            reset: "earliest"
        connector: smallrye-kafka
        topic: "Players.player_updated"

    outgoing:
      scorecard-added:
        connector: smallrye-kafka
        topic: "Scorecards.scorecard_added"
      scorecard-deleted:
        connector: smallrye-kafka
        topic: "Scorecards.scorecard_deleted"
      scorecard-updated:
        connector: smallrye-kafka
        topic: "Scorecards.scorecard_updated"
