avro:
  codegen:
    avsc:
      imports:
        - Action.avsc
        - RoundResult.avsc
        - ScoreEntry.avsc
        - CoursePayload.avsc
        - PlayerPayload.avsc
        - ScoreCardPayload.avsc
        - ScoreCardGroupedScoresPayload.avsc

quarkus:
  hibernate-orm:
    validate-in-dev-mode: true
  http:
    port: 8083
  liquibase:
    change-log: db/changelog.yaml
    contexts: all,dev # dev context inserts test data into db
    migrate-at-start: true

mp:
  messaging:
    connector:
      smallrye-kafka:
        apicurio:
          registry:
            avro:
              encoding: JSON
            auto-register: true

    incoming:
      course-state:
        topic: Courses-course_state
      player-state:
        topic: Players-player_state
      scores-incoming:
        topic: Scorecards-score_entries

    outgoing:
      scorecard-state:
        topic: Scorecards-scorecard_state
      scores:
        topic: Scorecards-score_entries
