quarkus:
  hibernate-orm:
    validate-in-dev-mode: true
  http:
    port: 8083
  liquibase:
    change-log: db/changelog.yaml
    contexts: all,dev # dev context inserts test data into db
    migrate-at-start: true

mp:
  messaging:
    connector:
      smallrye-kafka:
        apicurio:
          registry:
            avro:
              encoding: JSON
            auto-register: true

    incoming:
      course-added:
        topic: "Courses.course_added"
      course-deleted:
        topic: "Courses.course_deleted"
      course-updated:
        topic: "Courses.course_updated"
      hole-added:
        topic: "Courses.hole_added"
      hole-deleted:
        topic: "Courses.hole_deleted"
      hole-updated:
        topic: "Courses.hole_updated"
      player-state:
        topic: "Players.player_state"

    outgoing:
      scorecard-added:
        topic: "Scorecards.scorecard_added"
      scorecard-deleted:
        topic: "Scorecards.scorecard_deleted"
      scorecard-updated:
        topic: "Scorecards.scorecard_updated"
