avro:
  codegen:
    avsc:
      imports:
        - Action.avsc
        - RoundResult.avsc
        - ScoreEntry.avsc
        - CoursePayload.avsc
        - HolePayload.avsc
        - PlayerPayload.avsc
        - ScoreCardPayload.avsc
        - ScoreCardByPlayerPayload.avsc
        - ScoreCardByHolePayload.avsc

quarkus:
  hibernate-orm:
    validate-in-dev-mode: true
  http:
    port: 8083
  liquibase:
    change-log: db/changelog.yaml
    contexts: all,dev # dev context inserts test data into db
    migrate-at-start: true

mp:
  messaging:
    connector:
      smallrye-kafka:
        apicurio:
          registry:
            avro:
              encoding: JSON
            auto-register: true

    incoming:
      course-state:
        topic: "Courses-course_state"
      hole-state:
        topic: "Courses-hole_state"
      player-state:
        topic: "Players-player_state"

    # Send scorecards to two topics with different formats
    outgoing:
      scorecard-by-hole-state:
        topic: "Scorecards-scorecard_by_hole_state"
      scorecard-by-player-state:
        topic: "Scorecards-scorecard_by_player_state"
