quarkus:
  datasource:
    username: admin
    password: admin
    jdbc:
      url: jdbc:postgresql://localhost:5432/scorecards_db
  liquibase:
    contexts: all

kafka:
  bootstrap:
    servers: localhost:9092

mp:
  messaging:
    connector:
      smallrye-kafka:
        apicurio:
          registry:
            auto-register: true
            url: http://localhost:8001/apis/registry/v2
