quarkus:
  hibernate-orm:
    validate-in-dev-mode: true
  http:
    port: 8083
  liquibase:
    change-log: db/changelog.yaml
    contexts: all,dev # dev context inserts test data into db
    migrate-at-start: true

mp:
  messaging:
    incoming:
      course-added:
        auto:
          offset:
            reset: "earliest"
        connector: smallrye-kafka
        topic: "Courses.course_added"
        value:
          deserializer: io.apicurio.registry.serde.avro.AvroKafkaDeserializer
      course-deleted:
        auto:
          offset:
            reset: "earliest"
        connector: smallrye-kafka
        topic: "Courses.course_deleted"
        value:
          deserializer: io.apicurio.registry.serde.avro.AvroKafkaDeserializer
      course-updated:
        auto:
          offset:
            reset: "earliest"
        connector: smallrye-kafka
        topic: "Courses.course_updated"
        value:
          deserializer: io.apicurio.registry.serde.avro.AvroKafkaDeserializer
      hole-added:
        auto:
          offset:
            reset: "earliest"
        connector: smallrye-kafka
        topic: "Courses.hole_added"
        value:
          deserializer: io.apicurio.registry.serde.avro.AvroKafkaDeserializer
      hole-deleted:
        auto:
          offset:
            reset: "earliest"
        connector: smallrye-kafka
        topic: "Courses.hole_deleted"
        value:
          deserializer: io.apicurio.registry.serde.avro.AvroKafkaDeserializer
      hole-updated:
        auto:
          offset:
            reset: "earliest"
        connector: smallrye-kafka
        topic: "Courses.hole_updated"
        value:
          deserializer: io.apicurio.registry.serde.avro.AvroKafkaDeserializer
      player-added:
        auto:
          offset:
            reset: "earliest"
        topic: "Players.player_added"
      player-deleted:
        auto:
          offset:
            reset: "earliest"
        topic: "Players.player_deleted"
      player-updated:
        auto:
          offset:
            reset: "earliest"
        topic: "Players.player_updated"

    outgoing:
      score-added:
        apicurio:
          registry:
            auto-register: true
        connector: smallrye-kafka
        topic: "Scorecards.score_added"
      score-deleted:
        apicurio:
          registry:
            auto-register: true
        connector: smallrye-kafka
        topic: "Scorecards.score_deleted"
      scorecard-added:
        apicurio:
          registry:
            auto-register: true
        connector: smallrye-kafka
        topic: "Scorecards.scorecard_added"
      scorecard-deleted:
        apicurio:
          registry:
            auto-register: true
        connector: smallrye-kafka
        topic: "Scorecards.scorecard_deleted"
