# Uncomment lines if you are running infra locally and not using Quarkus Dev Services

quarkus:
  # datasource:
  #   username: admin
  #   password: admin
  #   jdbc:
  #     url: jdbc:postgresql://localhost:5432/scorecards_db
  hibernate-orm:
    validate-in-dev-mode: true
  http:
    port: 8083
  liquibase:
    change-log: db/changelog.yaml
    contexts: all,dev # dev context inserts test data into db
    migrate-at-start: true

# kafka:
#   bootstrap:
#     servers: localhost:9091

mp:
  messaging:
    connector:
      smallrye-kafka:
        apicurio:
          registry:
            auto-register: true
            # url: http://localhost:8000/apis/registry/v2

    incoming:
      course-added:
        auto:
          offset:
            reset: "earliest"
        connector: smallrye-kafka
        topic: "Courses.course_added"
      course-deleted:
        auto:
          offset:
            reset: "earliest"
        connector: smallrye-kafka
        topic: "Courses.course_deleted"
      course-updated:
        auto:
          offset:
            reset: "earliest"
        connector: smallrye-kafka
        topic: "Courses.course_updated"
      hole-added:
        auto:
          offset:
            reset: "earliest"
        connector: smallrye-kafka
        topic: "Courses.hole_added"
      hole-deleted:
        auto:
          offset:
            reset: "earliest"
        connector: smallrye-kafka
        topic: "Courses.hole_deleted"
      hole-updated:
        auto:
          offset:
            reset: "earliest"
        connector: smallrye-kafka
        topic: "Courses.hole_updated"
      player-added:
        auto:
          offset:
            reset: "earliest"
        connector: smallrye-kafka
        topic: "Players.player_added"
      player-deleted:
        auto:
          offset:
            reset: "earliest"
        connector: smallrye-kafka
        topic: "Players.player_deleted"
      player-updated:
        auto:
          offset:
            reset: "earliest"
        connector: smallrye-kafka
        topic: "Players.player_updated"

    outgoing:
      score-added:
        connector: smallrye-kafka
        topic: "Scorecards.score_added"
      score-deleted:
        connector: smallrye-kafka
        topic: "Scorecards.score_deleted"
      scorecard-added:
        connector: smallrye-kafka
        topic: "Scorecards.scorecard_added"
      scorecard-deleted:
        connector: smallrye-kafka
        topic: "Scorecards.scorecard_deleted"
      scorecard-updated:
        connector: smallrye-kafka
        topic: "Scorecards.scorecard_updated"
