quarkus:
  hibernate-orm:
    validate-in-dev-mode: true

  http:
    port: 8083

mp:
  messaging:
    outgoing:
      scores-out:
        topic: "Scorecards.score"
      scorecards-out:
        topic: "Scorecards.scorecard"

    incoming:
      course-added:
        auto:
          offset:
            reset: "earliest"
        topic: "Courses.course_added"
      course-deleted:
        auto:
          offset:
            reset: "earliest"
        topic: "Courses.course_deleted"
      course-updated:
        auto:
          offset:
            reset: "earliest"
        topic: "Courses.course_updated"
      hole-added:
        auto:
          offset:
            reset: "earliest"
        topic: "Courses.hole_added"
      hole-deleted:
        auto:
          offset:
            reset: "earliest"
        topic: "Courses.hole_deleted"
      hole-updated:
        auto:
          offset:
            reset: "earliest"
        topic: "Courses.hole_updated"
      players-in:
        auto:
          offset:
            reset: "earliest"
        topic: "Players.player"
