quarkus:
  hibernate-orm:
    validate-in-dev-mode: true

  http:
    port: 8083

mp:
  messaging:
    outgoing:
      scores-out:
        topic: "scores"
      scorecards-out:
        topic: "scorecards"

    incoming:
      courses-in:
        auto:
          offset:
            reset: "earliest"
        topic: "courses"
      holes-in:
        auto:
          offset:
            reset: "earliest"
        topic: "holes"
      players-in:
        auto:
          offset:
            reset: "earliest"
        topic: "players"
