developerName: Mika Alaoutinen

# Package settings
apiPackage: mikaa.api
modelPackage: mikaa.model
sourceFolder: src/main/java

# Java settings
booleanGetterPrefix: is
dateLibrary: java8

# code generation settings
documentationProvider: none
implicitHeaders: true
interfaceOnly: true
modelNameSuffix: DTO
openApiNullable: false
performBeanValidation: true
returnResponse: true
skipDefaultInterface: true
useTags: true
