quarkus:
  datasource:
    username: admin
    password: admin
    jdbc:
      url: jdbc:postgresql://localhost:5432/courses_db
  http:
    port: 8082
  liquibase:
    change-log: db/changelog.yaml
    contexts: all
    migrate-at-start: true

kafka:
  bootstrap:
    servers: localhost:9092

mp:
  messaging:
    connector:
      smallrye-kafka:
        apicurio:
          registry:
            auto-register: true
            url: http://localhost:8001/apis/registry/v2
