# Don't configure DB connection and let Quarkus dev mode handle it
quarkus:
  hibernate-orm:
    validate-in-dev-mode: true
  http:
    port: 8082
  liquibase:
    change-log: db/changelog.yaml
    contexts: all,dev # dev context inserts test data into db
    migrate-at-start: true

mp:
  messaging:
    outgoing:
      course-added:
        topic: "Courses.course_added"
      course-deleted:
        topic: "Courses.course_deleted"
      course-updated:
        topic: "Courses.course_updated"
      holes-out:
        topic: "Courses.hole"
