# A "production" profile that uses an existing Postgres DB.
quarkus:
  datasource:
    jdbc:
      url: ${db_url:jdbc:postgresql://localhost:5432/course_db}
    username: ${db_username:admin}
    password: ${db_password:admin}
  hibernate-orm:
    validate-in-dev-mode: true

  http:
    port: 8082
    root-path: /api

kafka:
  bootstrap:
    servers: localhost:9092

mp:
  messaging:
    outgoing:
      courses-out:
        topic: "courses"
    incoming:
      courses-in:
        auto:
          offset:
            reset: "earliest"
        topic: "courses"
