# Don't configure DB connection and let Quarkus dev mode handle it
quarkus:
  hibernate-orm:
    validate-in-dev-mode: true
  http:
    port: 8082
  liquibase:
    change-log: db/changelog.yaml
    contexts: all
    migrate-at-start: true

mp:
  messaging:
    outgoing:
      courses-out:
        topic: "courses"
      holes-out:
        topic: "holes"

# Must define profile based configuration like this instead of using an application-dev.yaml
# file, because Quarkus ignores the dev file even though it should work.
"%dev":
  quarkus:
    liquibase:
      contexts: all,dev
