quarkus:
  hibernate-orm:
    validate-in-dev-mode: true
  http:
    port: 8082
  liquibase:
    change-log: db/changelog.yaml
    contexts: all,dev # dev context inserts test data into db
    migrate-at-start: true

mp:
  messaging:
    connector:
      smallrye-kafka:
        apicurio:
          registry:
            avro:
              encoding: JSON
            auto-register: true

    outgoing:
      course-state:
        topic: "Courses.course_state"
      hole-state:
        topic: "Courses.hole_state"
