# Don't configure DB connection and let Quarkus dev mode handle it
quarkus:
  http:
    port: 8082
    root-path: /api

mp:
  messaging:
    outgoing:
      words-out:
        topic: "words"
    incoming:
      words-in:
        auto:
          offset:
            reset: "earliest"
        topic: "words"
