# Don't configure DB connection and let Quarkus dev mode handle it
quarkus:
  hibernate-orm:
    validate-in-dev-mode: true
  http:
    port: 8082
  liquibase:
    change-log: db/changelog.yaml
    contexts: all,dev # dev context inserts test data into db
    migrate-at-start: true

mp:
  messaging:
    outgoing:
      courses-out:
        topic: "courses"
      holes-out:
        topic: "holes"
