quarkus:
  datasource:
    username: admin
    password: admin
    jdbc:
      url: jdbc:postgresql://localhost:5432/courses_db
  http:
    port: 8082
  liquibase:
    change-log: db/changelog.yaml
    contexts: all
    migrate-at-start: true

kafka:
  bootstrap:
    servers: localhost:9092

mp:
  messaging:
    connector:
      smallrye-kafka:
        apicurio:
          registry:
            auto-register: true
            url: http://localhost:8001/apis/registry/v2

    outgoing:
      course-added:
        connector: smallrye-kafka
        topic: "Courses.course_added"
      course-deleted:
        connector: smallrye-kafka
        topic: "Courses.course_deleted"
      course-updated:
        connector: smallrye-kafka
        topic: "Courses.course_updated"
      hole-added:
        connector: smallrye-kafka
        topic: "Courses.hole_added"
      hole-deleted:
        connector: smallrye-kafka
        topic: "Courses.hole_deleted"
      hole-updated:
        connector: smallrye-kafka
        topic: "Courses.hole_updated"
