greeting:
  message: "hello"

quarkus:
  datasource:
    jdbc:
      url: jdbc:postgresql://localhost:5432/course_db
    username: admin
    password: admin
  hibernate-orm:
    validate-in-dev-mode: true

  http:
    port: 8082
    root-path: /api

mp:
  messaging:
    outgoing:
      words-out:
        topic: "words"
    incoming:
      words-in:
        auto:
          offset:
            reset: "earliest"
        topic: "words"
