@url = http://localhost:8081/players

### get all
GET {{url}} HTTP/1.1

### get all with filter
GET {{url}}?name=Pekka HTTP/1.1

### get one
GET {{url}}/4 HTTP/1.1

### get one that doesn't exist
GET {{url}}/99 HTTP/1.1
