name: Score cards service feature branch

on:
  push:
    branches-ignore:
      - master
      - release*
    paths:
      - scorecards-service/**

jobs:
  build:
    name: Build and run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
      - name: Build and test with Maven
        run: mvn -B clean verify --file ./scorecards-service/pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
