name: Queries streams Master branch

on:
  push:
    branches:
      - master
    paths:
      - queries-service-streams/**

jobs:
  build:
    name: Build and run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"
      - name: Build and test with Maven
        run: mvn -B clean install --file ./queries-service-streams/pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
